include: package:flutter_lints/flutter.yaml # https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    always_declare_return_types: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    # Disabled due to the usage in manual `fromJSON` implementations, will be removed once we can make use of the JSON macro in tests & the example
    argument_type_not_assignable: ignore
    avoid_bool_literals_in_conditional_expressions: error
    avoid_catching_errors: error
    avoid_double_and_int_checks: error
    avoid_empty_else: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_escaping_inner_quotes: error
    avoid_field_initializers_in_const_classes: error
    avoid_function_literals_in_foreach_calls: error
    avoid_init_to_null: error
    avoid_js_rounded_ints: error
    avoid_null_checks_in_equality_operators: error
    avoid_returning_null_for_future: error
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_shadowing_type_parameters: error
    avoid_single_cascade_in_expression_statements: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    avoid_void_async: error
    avoid_web_libraries_in_flutter: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    cancel_subscriptions: error
    close_sinks: error
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: error
    do_not_use_environment: error
    empty_catches: error
    empty_constructor_bodies: error
    empty_statements: error
    exhaustive_cases: error
    file_names: error
    flutter_style_todos: error
    hash_and_equals: error
    implementation_imports: error
    invariant_booleans: error
    iterable_contains_unrelated_type: error
    join_return_with_assignment: error
    leading_newlines_in_multiline_strings: error
    library_names: error
    library_prefixes: error
    list_remove_unrelated_type: error
    missing_required_param: error
    missing_return: error
    unused_import: error

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_iterable_whereType
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - test_types_in_equals
    - type_annotate_public_apis
    - unawaited_futures
    - unrelated_type_equality_checks
    - use_super_parameters
